/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package schedulepro;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sasi Praveen
 */
public class AssignFacultytoExamForm extends javax.swing.JFrame {

    private int examCode = 0;
    private String examDate = "";
    private boolean flag = false;
    private String Query;
    private boolean assigned = false;
    private String excode="";

    /**
     * Creates new form AssignFacultytoExamForm
     */
    public AssignFacultytoExamForm() {
        initComponents();

        examCode = ExamScheduleViewForm.examCode;
        examDate = ExamScheduleViewForm.examDate;
        ResultSet result = Utilfunctions.executeQuery("select userCode from examinvigilation where examCode=" + examCode);
        try {
            if (result.next()) {
                ResultSet result1 = Utilfunctions.executeQuery("SELECT CONCAT(name,'(',userCode,')') FROM `user` WHERE userCode='" + result.getString(1) + "'");
                result1.next();
                assignedFacultyTextField.setText(result1.getString(1));
                flag = true;
                assignButton.setText("change");
                this.setTitle("SchedulePro - Change Faculty");
            } else {
                assignedFacultyTextField.setText("");
                flag = false;
                assignButton.setText("Assign");
                this.setTitle("SchedulePro - Assign Faculty");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AssignFacultytoExamForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        Query = "SELECT CONCAT(name,'(',userCode,')') FROM user WHERE  dept =  '" + LoginForm.userDept + "' order by name asc";
        result = Utilfunctions.executeQuery(Query);
        ResultSet r1;
        ResultSet r2;
        try {
            while (result.next() != false) {
                assigned = false;
                Query = "select examCode from examinvigilation where userCode = '" + Utilfunctions.getWithinBrackets(result.getString(1)) + "'";
                r1 = Utilfunctions.executeQuery(Query);
                while (r1.next()) {
                    Query = "select examDate from exam where examCode = " + r1.getString(1);
                    r2 = Utilfunctions.executeQuery(Query);
                    r2.next();
                    if (r2.getString(1).equals(examDate)) {
                        assigned = true;
                        excode = r1.getString(1);
                        break;
                    }
                }
                if (assigned) {
                    changeFacultyComboBox.addItem("<html><font color=red>" + result.getString(1) + "</font></html>");
                } else {
                    changeFacultyComboBox.addItem("<html><font color=green>" + result.getString(1) + "</font></html>");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        assignedFacultyTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        changeFacultyComboBox = new javax.swing.JComboBox();
        assignButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SchedulePro - Change Faculty");
        setResizable(false);

        jLabel1.setText("Assigned Faculty:");

        assignedFacultyTextField.setEditable(false);

        jLabel2.setText("Change Faculty:");

        assignButton.setText("Assign");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changeFacultyComboBox, 0, 189, Short.MAX_VALUE)
                    .addComponent(assignedFacultyTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(assignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(assignedFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(changeFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(assignButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        // TODO add your handling code here:
        ResultSet r1;
        ResultSet r2;
        ResultSet r3;
        if (changeFacultyComboBox.getSelectedItem().toString().contains("green")) {
            if (flag) {
                Utilfunctions.executeUpdate("UPDATE `examinvigilation` SET `userCode`='" + Utilfunctions.getWithinBrackets(changeFacultyComboBox.getSelectedItem().toString()) + "' WHERE `examCode`=" + examCode);
            } else {
                Utilfunctions.executeUpdate("INSERT INTO `examinvigilation`(`id`, `examCode`, `userCode`) VALUES (NULL," + examCode + ",'" + Utilfunctions.getWithinBrackets(changeFacultyComboBox.getSelectedItem().toString()) + "')");
            }
            this.setVisible(false);
        } else {
            try {
                r1 = Utilfunctions.executeQuery("select examDate, classCode, subCode from exam where examCode ="+excode);
                r1.next();
                r2 = Utilfunctions.executeQuery("select CONCAT(subName,'(',subcode,')') from subject where subcode = '"+r1.getString(3)+"'");
                r2.next();
                r3 = Utilfunctions.executeQuery("select year, course, section, roomNo from class where classCode = "+r1.getString(2));
                r3.next();
                JOptionPane.showMessageDialog(null, "Alreay assigned to:\nSubject = "+r2.getString(1)+"\nClass = "+r3.getString(1)+"-"+r3.getString(3)+" "+r3.getString(2)+"\nRoom No. = "+r3.getString(4));
            } catch (SQLException ex) {
                Logger.getLogger(AssignFacultytoExamForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_assignButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignFacultytoExamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignFacultytoExamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignFacultytoExamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignFacultytoExamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignFacultytoExamForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignButton;
    private javax.swing.JTextField assignedFacultyTextField;
    private javax.swing.JComboBox changeFacultyComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
