/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package schedulepro;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Sasi Praveen
 */
public class AssignFacultyForm extends javax.swing.JFrame {

    /**
     * Creates new form AssignFacultyForm
     */
    public AssignFacultyForm() {
        initComponents();
        Utilfunctions.populateComboBoxwithQuery(selectCourseComboBox, "SELECT DISTINCT(`course`) FROM `class` WHERE dept='"+LoginForm.userDept+"'");
        Utilfunctions.populateComboBoxwithQuery(selectSubjectComboBox, "select CONCAT(`subName`,'(',`subcode`,')') from `subject` WHERE `dept`='"+LoginForm.userDept+"' order by `subName` asc");
        Utilfunctions.populateComboBoxwithQuery(selectFacultyComboBox, "SELECT CONCAT(`name`,'(',`userCode`,')') FROM `user` WHERE `dept`='"+LoginForm.userDept+"' order by `name` asc");
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                DashboardForm df = new DashboardForm();
                Utilfunctions.setIconImage(df);
                Utilfunctions.setLocation(df);
                e.getWindow().setVisible(false);
                df.setVisible(true);

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectYearLabel = new javax.swing.JLabel();
        selectYearComboBox = new javax.swing.JComboBox();
        selectSectionLabel = new javax.swing.JLabel();
        selectSectionComboBox = new javax.swing.JComboBox();
        selectSubjectLabel = new javax.swing.JLabel();
        selectSubjectComboBox = new javax.swing.JComboBox();
        saveButton = new javax.swing.JButton();
        selectFacultyLabel = new javax.swing.JLabel();
        selectFacultyComboBox = new javax.swing.JComboBox();
        selectCourseLabel = new javax.swing.JLabel();
        selectCourseComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SchedulePro - Assign Faculty");
        setResizable(false);

        selectYearLabel.setText("Select Year:");

        selectSectionLabel.setText("Select Section:");

        selectSubjectLabel.setText("Select Subject:");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        selectFacultyLabel.setText("Select Faculty:");

        selectCourseLabel.setText("Select Course:");

        selectCourseComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectCourseComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectSectionLabel)
                                .addGap(1, 1, 1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(selectCourseLabel)
                                .addComponent(selectYearLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectSectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(selectFacultyLabel)
                            .addComponent(selectSubjectLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectSubjectComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 196, Short.MAX_VALUE)))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectCourseLabel)
                    .addComponent(selectCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectYearLabel)
                    .addComponent(selectYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectSectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSectionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectSubjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSubjectLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFacultyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet result = Utilfunctions.executeQuery("SELECT `classCode` FROM `class` WHERE `year`=" + selectYearComboBox.getSelectedItem() + " AND `section`='" + selectSectionComboBox.getSelectedItem() + "' AND dept='"+LoginForm.userDept+"'");
            result.next();
            int n = Utilfunctions.executeUpdate("INSERT INTO `subclass`(`subClassId`, `classCode`, `subCode`, `userCode`) VALUES (NULL," + result.getString(1) + ",'" + Utilfunctions.getWithinBrackets(selectSubjectComboBox.getSelectedItem().toString()) + "','" + Utilfunctions.getWithinBrackets(selectFacultyComboBox.getSelectedItem().toString()) + "')");
            if (n == 1) {
                JOptionPane.showMessageDialog(null, "Saved");
            } else {
                JOptionPane.showMessageDialog(null, "Error in Saving");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No such Class Exists");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void selectCourseComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectCourseComboBoxItemStateChanged
        // TODO add your handling code here:
        Utilfunctions.populateComboBoxwithQuery(selectYearComboBox, "SELECT distinct(`year`) FROM `class` WHERE `dept`='"+LoginForm.userDept+"' AND course='"+selectCourseComboBox.getSelectedItem()+"' order by `year` asc");
        Utilfunctions.populateComboBoxwithQuery(selectSectionComboBox, "SELECT distinct(`section`) FROM `class` WHERE `dept`='"+LoginForm.userDept+"' AND course='"+selectCourseComboBox.getSelectedItem()+"' order by `section` asc");
    }//GEN-LAST:event_selectCourseComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignFacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignFacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignFacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignFacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignFacultyForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox selectCourseComboBox;
    private javax.swing.JLabel selectCourseLabel;
    private javax.swing.JComboBox selectFacultyComboBox;
    private javax.swing.JLabel selectFacultyLabel;
    private javax.swing.JComboBox selectSectionComboBox;
    private javax.swing.JLabel selectSectionLabel;
    private javax.swing.JComboBox selectSubjectComboBox;
    private javax.swing.JLabel selectSubjectLabel;
    private javax.swing.JComboBox selectYearComboBox;
    private javax.swing.JLabel selectYearLabel;
    // End of variables declaration//GEN-END:variables
}
